### ISSUE TITLE
Fixes for AGS3 SDL2 port

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1148]
Issue to aggregate remaining fixes for AGS3 SDL2 port (now merged into master).

### All Ports

- Sound config: device(?)  (moved to #1565)
- Threaded audio option is now working differently (disable? or keep it still because Emscripten port requires one) (moved to #1566)
- "Software" SDL Renderer output hinting config (moved to #1567)

---

### Windows

- Update winsetup (sound config, perhaps something else?) (moved to #1565)

---

### Linux

- [ ] Restore setting icon.xpm, see #1410 explaining the issues met.

---

### MacOS

- [ ]  Not exactly a task, but the port needs more testing. 
- [ ]  Update build instructions. (cmake generates xcode project or cmake builds directly, mention SDL2 framework)

---

### Android

- [ ]  Touch to mouse translation auto translated from SDL2 is not similar to old Android backend behavior. On a plus it allows drag and drop module to work, finger hold on screen is readable by mouse.IsButtonDown(): https://youtu.be/lbdth4SHbSE.

---

### iOS

iOS support is a bit tricky (for me), SDL2 supports but I lack the device to test it, so for now I think the main task is finding someone who is interested in picking it up. If no one picks it up, I can do it on an emulator.

https://hg.libsdl.org/SDL/file/bc96d65e47da/docs/README-cmake.md
https://hg.libsdl.org/SDL/file/bc96d65e47da/docs/README-ios.md

mapped on #1505

---
## Completed Tasks

<details><summary>Click to Expand - Finished Tasks hidden for readability</summary>
<p>

~~I marked with one asterisk `*` what is reasonably done but hasn't been merged yet, and with two asterisk `**` what the fix is made but isn't completely working yet and hasn't been merged.~~ Probably not relevant anymore, but kept for history.

### All Ports

- [x] missing proper sound cancellation, [see comment]()https://github.com/adventuregamestudio/ags/issues/1148#issuecomment-761581778
- [x] Sound subsystem and thread has to be explicitly stopped on exit before shutting down backend and deleting data, otherwise there may be errors.
- [x] CI/CMake update: don't use DirectX SDK anymore. (#1291)
- [x] CI/CMake update: don't require DirectX SDK and SDL2/SDL_sound for editor. (#1291)
- [x]  Remove `hqx` filter mention from command line arguments (#1293)
- [x] ~~Unresolved import DrawSprite (I think this was already solved at some point, happens when running  Hell's Puppy -> https://github.com/ericoporto/dogfromhell)~~ error was the thing between the chair and the computer.
- [x]  Mouse Middle Click, with  `on_mouse_click(MouseButton b)` callback, is not working. [mouseMiddleClickTest.zip](https://github.com/adventuregamestudio/ags/files/5668991/mouseMiddleClickTest.zip) (middle click should Display a text).
- [x]  ~Ctrl+~Alt+X doesn't abort the game. 
- [x]  Add support to Window Resizing in desktop OSes
- [x] Support SDL_WINDOW_FULLSCREEN along with SDL_WINDOW_FULLSCREEN_DESKTOP (in fact, maybe just add generic "desktop fullscreen" config option and apply "fullscreen" only where possible (SDL renderer and Direct3D).

### Windows

- [x] Put prebuilt libraries in a more conventional place (e.g. github repo). (fixed by #1390)
- [x] If we are using a separate SDL2.dll, then it needs to be added in the Editor packaging pipeline (and in the installer) (#1368)
- [x]  Editor doesn't put SDL2.dll together in the directory / alternatively, use SDL2 statically linked
- [x] Update license files in the win installer folder(#1345)
- [x]  I don't know if others have this issue, but errors place the pop-up window behind the game window and if the game is Fullscreen I can't close it or load task manager, having to restart my computer. Maybe related to #1034 
- [x] Investigate using newer Directx SDK ([see comment](https://github.com/adventuregamestudio/ags/issues/1148#issuecomment-757144368))Fullscreen I can't close it or load task manager, having to restart my computer. Maybe related to #1034 
- [x]  Fix CI system.  `*` PR: #1141 
- [x]  Update build instructions.
- [x] write code for `sys_window_set_icon`. (PR #1410 )

### Linux

- [x]  Debian packaging. SDL_sound has to be statically linked since it's package is not updated. #1159 
- [x] Update Licenses. 
- [x]  Fix CI system.  `**` (missing debian parts) #1157 
- [x]  Update Editor code that builds the port.
- [x]  Update build instructions. (change of dependencies)

### MacOS

- [x]  Minor fixes on allegro and engine code. `*` #1152 

### Android
- [x]  Java completely rewritten to use SDL2 class instead of AGS Glue. `*`
- [x]  Launcher (Java code) has to be redone.
- [x]  Optionally, add single game launcher (Java code) in the AGS repository.
- [x]  Use of CMake builds for Android to easily adapt to Android build system changes, it also reduces code. `*`
- [x]  Restore or not usage of android.cfg, some options relied on Allegro4 android backend.drag and drop module to work, finger hold on screen is readable by mouse.IsButtonDown(): https://youtu.be/lbdth4SHbSE.
- [x]  Add OpenGL ES2 support, wasn't available on previous port in the ags3 branch, but I have the code already written and it works best with newer android devices. `*`
- [x]  Delete unused code. Some old specific Allegro4 Android code can be deleted.
- [x]  Update build instructions. (`./gradlew build` or load the project in Android Studio, mention SDK and NDK versions)

https://hg.libsdl.org/SDL/file/default/docs/README-android.md

</p>
</details>

---

If more issues are found or something is missing, please write about it below.

**Comment by ivan-mogilko** [comment]
By the way, SDL2 devs fixed my reported bug :)
https://bugzilla.libsdl.org/show_bug.cgi?id=5329

I think they target 2.0.14 release, so we may update when it's out.

**Comment by ericoporto** [comment]
Ha, very cool! 😃

One thing I remembered is there were some TO-DOs on the sound part but I don't remember if they are supposed to be in the list above. 😬

**Comment by ivan-mogilko** [comment]
Something that might be added:
- sound config, affecting selected driver (right now it's a simple on-off switch)
- config option for software renderer that defines preferred output type (used when creating SDL_Renderer)

There were some problems which I met while testing random games, but I ignored them temporarily. I'd need to repeat tests and document these.

**Comment by ivan-mogilko** [comment]
Oh, also support resizing window on desktop oses; I skipped that for simplicity but it was supported in sonneveld's branch.

**Comment by ericoporto** [comment]
Added above in the list :)

**Comment by ivan-mogilko** [comment]
I was a bit distracted for a while, is my understanding correct that macos builds and works with SDL2 now?
Desktop OSes are my primary concern before merging this into master and ags4.
Applying Android changes is my first next todo. iOS may wait, because it's more niche and usually commercial gamedevs do their own fixes for it anyway.

---

On another topic, I was supplying prebuilt libraries for Windows in my dropbox. Is there any option to do so on github? I know one could attach these to release, but this seem an obscure place, as the links should stay permanent for a long while.

**Comment by ericoporto** [comment]
It worked on my Mojave box and High Sierra, yes. I haven't tried on the more recent MacOSes - but I believe it should. I can make a Catalina test but I don't have access to the latest Big Sur yet.

I am working on Android here: [ericoporto/ags/ags3--sdl2-android](https://github.com/ericoporto/ags/tree/ags3--sdl2--android) and picking up the latest Android project from my own main branch for merging. Just haven't being able to finish yet.

---

I made a NuGet package for the xiph libraries but just them here: https://github.com/ericoporto/xiph-for-ags

I made it build and upload using only Azure to avoid manual steps, I could make something like this. I actually used it on the Windows Docker to avoid a vcpkg bug on our CI, but maybe a proper repo for Windows prebuilt binaries could exist in ags org, with it's own releases. I didn't went through, but by shipping it's own `.prop` file in it, the NuGet library can even be part of the Windows VS Solution itself if desired.

Other than making a separate repository for ags dependencies on Windows, GitHub has a packages feature that I haven't explored but I may be able to serve just that.

**Comment by rofl0r** [comment]
> Other than making a separate repository for ags dependencies on Windows

this seems to be a good choice. i've seen various orgas on github that put their releases/binaries into dedicated repos. the files will stay available using a link with commit hash even if they are replaced in subsequent commits, unless the commits adding them become orphans (e.g. with a force-push removing them). an alternative could be sourceforge or osdn.net (located in japan).

**Comment by ivan-mogilko** [comment]
+ Update license files in the win installer folder

**Comment by ericoporto** [comment]
Added to the list!

**Comment by ivan-mogilko** [comment]
Something I forgot to test earlier, but I suspect that we may use slightly less old DirectX SDK. There was a need to use particular "August 2007" version because it contained headers necessary for Allegro 4 graphic and input drivers.

As a part of commit ae8b7369e92e2091180e27fae2cfa7dfa8a1bb0a I've removed following linked libs: ddraw.lib, dinput.lib, dsound.lib, dxguid.lib. The only lib still required is d3d9.lib (for Direct3D renderer). This means we may try to use latest SDK that still supports Direct3D 9 (iirc from 2008 or 2009).

**Comment by ivan-mogilko** [comment]
Found bug in new sound backend: it does not have a proper cancellation in case it failed to decode sound data.
If the clip is told to play repeatedly it gets into infinite loop trying to fill the buffer over and over again.

**Comment by ivan-mogilko** [comment]
MIDI playback is broken currently. I don't remember if it happens for any midi files, but in [this game](https://github.com/adventuregamestudio/ags/files/5811535/larry2_repack.zip) for instance midi music sounds like 5-10 times slower when run on Windows.

**Comment by ivan-mogilko** [comment]
+ removed vorbisfile from Windows version, need to double check that it still works if we remove it from other ports (linux etc); simply did not have time to test it myself yet.

**Comment by ivan-mogilko** [comment]
Merged latest ags3 branch, DrawSprite fix should be there now, and maybe something else.

**Comment by rofl0r** [comment]
> but in this game for instance midi music sounds like 5-10 times slower when run on Windows.

this sounds like the bug i reported to SDL bugtracker which is the result of libmodplug not finding midi instruments (mentioned in #367)

**Comment by ericoporto** [comment]
Just heads-up, SDL is migrating to GitHub: https://github.com/libsdl-org/SDL

**Comment by rofl0r** [comment]
> Just heads-up, SDL is migrating to GitHub: https://github.com/libsdl-org/SDL

that's great. though i can't find any official announcement of the move, did you see one?
the sdl hp also still links to their hg repo which has seen recent commits as of 20 hrs ago.

**Comment by ericoporto** [comment]
> Merged latest ags3 branch, DrawSprite fix should be there now, and maybe something else

Sorry, I have rebased and am still hitting DrawSprite error. I confirmed it also happens on Linux build. I think it's from agsblend, but I have the plugins built-in, plus I really do remember this specific error being fixed but I couldn't find the commit.

![Screenshot_20210121-220300_AGS Player](https://user-images.githubusercontent.com/2244442/105431500-82f3c280-5c34-11eb-8de8-a5fe7eab1aea.jpg)

**Comment by ivan-mogilko** [comment]
I confused this with DrawImage bug. DrawSprite is probably from agsblend plugin?

**Comment by ericoporto** [comment]
You are right, I confused one error with the other too! Turns out I thought I had built the Engine with built-in plugins but I didn't. Sorry for the confusion.

**Comment by ericoporto** [comment]
![Screenshot_20210124-094300_AGS Player](https://user-images.githubusercontent.com/2244442/105630574-c31b9680-5e28-11eb-9c21-234c87c1d73e.jpg)

Hey, I am trying to make the new SDL "Software" Renderer to work on Android and I am trying to figure out how to stretch it through the screen. I looked at source code and the new SDL Software Renderer is different from the one that was before (that one had other bugs though), anyway any guesses on where to look for why it's not stretching?

I tried using AGS Script API to alternate between windowed mode and fullscreen, and while windowed makes the game correctly stretch in the non-fullscreen area, going back to fullscreen after still makes the game tiny.

**Comment by ivan-mogilko** [comment]
I could look into this when I find spare time. If I remember correctly the old pre-SDL renderer worked in similar principle, but essential difference was that the conversion into opengl texture and stretching was done inside patched allegro library.

So my guess would be that android backend simply does not pass final screen resolution to the engine, because it was not done before. *Maybe* it should work just how our OpenGL renderer works now - there is some functions or variables that retrieve device resolution.

**Comment by rofl0r** [comment]
i've found this guide quite good: https://wiki.libsdl.org/MigrationGuide#Moving_from_SDL_1.2_to_2.0

if i remember correctly, one basically just has to fill a surface with pixel data in the original format and depending on fullscreen settings the chosen rendered will stretch it to screen size either in sw or hw.

**Comment by ivan-mogilko** [comment]
> if i remember correctly, one basically just has to fill a surface with pixel data in the original format and depending on fullscreen settings the chosen renderer will stretch it to screen size either in sw or hw.

Yes, this practically what we do now:
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Engine/gfx/ali3dsw.cpp#L501

**Comment by ericoporto** [comment]
Thanks dudes! I will eat lunch and rellax a little and take a look later today. I have followed things with a debugger and haven't found anything yet but I haven't dived into SDL itself. One thing weird is I found a specific game (Suli) that is working correctly with it on Android! I also advanced a bit on CI and organizing commits and am thinking to at least have a working WIP PR just to see how it goes.

**Comment by ivan-mogilko** [comment]
Well, sounds like it already changed beyond my knowledge.

**Comment by ericoporto** [comment]
I got it working, I still didn't managed to finish some small details in the new docker image for the CI but hopefully I can finish during this week.

**Comment by ivan-mogilko** [comment]
@ericoporto quickly looking at the branch in your repo, there are couple things that bother me. One is related to "gml" library addition which is then used in code in commit named "ES2 support". I was thinking to investigate if this may be separated, but since you took over this, could you tell if this is necessary because ES2 no longer supports GL own matrix functions, or was done only for the reason of adding glm?

If latter, I'd propose to remove this from android pr, and consider adding separately (and there are more places where we may utilize matrix functions where we dont want to depend on opengl).

There are couple of other things, but these may be less time consuming to fix, so I'd discuss them in pr thread when it's ready.

**Comment by ericoporto** [comment]
Previous OpenGL renderer was really dependant of the custom backend made in Allegro and it just doesn't work on my main phone - and I have zero idea on how to make it work with SDL2. ES2 does drawing through shaders - no [glColor4f](https://stackoverflow.com/questions/23794053/opengl-2-0-glcolor4f-not-working). It also doesn't have matrix functions, which is why I used glm for those. I have used and maintained the core of this renderer for two years now. Without it I can't test - older phones use a different API for Debug and I can't produce proper tracing on latest Android Studio. If you look closer the new code is just like your OGL renderer but with the an additional transparency shader, and also just removed the non ES2 gl functions. Perhaps you are looking at the wrong branch?

https://github.com/ericoporto/ags/tree/ags3--sdl2--android-5

For now I have been pushing force a lot trying to properly rewrite the commits so things makes sense.

**Comment by rofl0r** [comment]
> few things that bother me. One is "gml" library addition 

i second this. we shouldn't pull in a new 3rd party library everytime an issue pops up that would require to write a few dozen lines of code to solve it.

**Comment by ivan-mogilko** [comment]
> ES2 does drawing through shaders - no glColor4f. It also doesn't have matrix functions

Okay, this is the reason then.

**Comment by ericoporto** [comment]
You are free to write a better matrix library for me. 

ES1 doesn't support shaders on Android: https://developer.android.com/guide/topics/graphics/opengl

**Comment by ivan-mogilko** [comment]
BTW we had to write our own matrix functions for Direct3D for the reason to not link with some utility lib from Windows SDK.
(First were written by Chris Jones, and I amended them later)

> Directx matrix is different from OpenGL, I think it needs some conversion.

Afaik they need only a transpose operation, because they have columns and rows switch

**Comment by ivan-mogilko** [comment]
>  I can also alternatively use glm and remove anything that is not mat4 of it so it's tinier - it reduces to 6 headers I think.

Yes that would be nice to only include what is strictly necessary for now. (Unless there's some problem with glm license)

**Comment by ericoporto** [comment]
I will look on how I can reduce it. I really want to use it because it builds very efficiently on WASM and this is the WebGL renderer already - maybe it won't exist in ags3 but it would be cool to have ags4 able to do WebGL builds.

**Comment by ericoporto** [comment]
I looked into and it's just not worth it trying to reduce to less than the 60k loc in 400kb it has, so I won't. Anyone else is free to try. I don't understand why other things in the repository gets a free pass to inclusion in the repository - like Freetype.

**Comment by rofl0r** [comment]
> I don't understand why other things in the repository gets a free pass to inclusion in the repository - like Freetype.

freetype was already a dependency, we just added the exact ancient version that's required to not break old games using the lucasarts fonts.

it's another thing to add a new library for every task, especially when the motivation is "hey this library is cool i like to use it somewhere". it's similar to "hey i'd like to use this cool new C++20 feature so let's throw compatibility over board"

**Comment by rofl0r** [comment]
> BTW a clean build of ags including fetching and building all dependencies on my pc is 20 seconds on CMake.

your PC is super fast. compiling AGS takes more than 5 mins on mine. i even wrote this script:

```sh
#!/bin/sh --

## cachecc (c) 2021 rofl0r
##
## wrapper for gcc/g++, which only recompiles .o file when input dependencies
## have changed. this is useful when working on C++ projects that have huge
## compile times, and switching between branches with git e.g. simply for
## looking at files, will cause git to modify the timestamp of any file that's
## been touched by any commit, forcing make to rebuild it later when you switch
## to a branch you actually work on.
##
## also helpful: when CACHECC_VERBOSE=1 is set in the environment, one can
## actually see why a file is being scheduled for rebuild by make - often it's
## a tiny innocent change to a header that causes a forced rebuild of dozens
## of files.
##
## the wrapper stores command line and hashes for all input files in a file
## with a .cachedat extension, so if you want a forced rebuild of a project
## (e.g. when some system headers have changed) you can simply execute
## find -name '*.cachedat' -delete and you have a clean state.
##
## usage: put cachecxx into your PATH and symlink it to cachecc (for C).

toolname="$(basename "$0")"
if test "$toolname" = "cachecxx" ; then
CALL_COMPILER=g++
EXTS="cpp cc C"
else
CALL_COMPILER=gcc
EXTS="c"
fi
verbose=false
test -n "$CACHECC_VERBOSE" && verbose=true

getmd5() { md5sum | cut -d ' ' -f 1 ; }
getmd5f() { md5sum "$1" | cut -d ' ' -f 1 ; }
# some helper functions taken from musl's configure
fnmatch () { eval "case \"\$2\" in $1) return 0 ;; *) return 1 ;; esac" ; }
quote () {
tr '\n' ' ' <<EOF | grep '^[-[:alnum:]_=,./:]* $' >/dev/null 2>&1 && { echo "$1" ; return 0 ; }
$1
EOF
printf %s\\n "$1" | sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" -e "s#^'\([-[:alnum:]_,./:]*\)=\(.*\)\$#\1='\2#"
}
gettmp(){
i=0
set -C
while : ; do i=$(($i+1))
tmpf="./cachetmp$$-$PPID-$i.d"
2>|/dev/null > "$tmpf" && break
test "$i" -gt 50 && fail "$0: cannot create temporary file $tmpf"
done
set +C
trap 'rm -f "$tmpf"' EXIT INT QUIT TERM HUP
}
deps() {
# turn output of gcc -E -MM into one line per dependency, remove the target
# and trailing backslashes before newlines.
awk 'BEGIN {skipf=1;} function out(a,j){for(j=1;j<=length(a);++j)if(substr(a,j,1)=="\\"){++j;printf("%s", substr(a,j,1));}else printf("%s", substr(a,j,1));printf("\n");} {if(skipf == 1){ for(i=1; substr($0,i,1) != ":"; ++i); $0=substr($0,i+1); skipf=0;} start=2; for(i=start; i<=length($0); ++i) {if(substr($0,i,1)=="\\")++i; else if(substr($0,i,1)==" ") {out(substr($0,start,i-start)); start=i+1;} } if(i>start&&substr($0,start,i-start)!="\\") out(substr($0,start,i-start));}' <$tmpf
}
gencache() {
# $@ manipulation technique provided by earnestly
gettmp
c=$#
while [ "$c" -ne 0 ]; do
 case $1 in
  -c) ;;
  -o) shift ;;
  *) set -- "$@" "$1"
 esac
 shift
 c=$((c - 1))
done
$CALL_COMPILER "$@" -E -MM -MF $tmpf || return 1
printf "%s\n" "$opts_hash" > "$outfile.cachedat"
c=0
s_IFS="$IFS"
IFS='
'
for x in $(deps) ; do
printf "%s:%s\n" "$(getmd5f "$x")" "$x" >> "$outfile.cachedat"
done
IFS=s_IFS
rm -f "$tmpf"
}
recompile() {
gencache "$@"
exec $CALL_COMPILER "$@"
}

infile=
outfile=
minus_c_seen=false
next_is_out=false

for arg ; do
 if test x${arg}x = x-cx ; then
  minus_c_seen=true
 elif test x${arg}x = x-ox ; then
  next_is_out=true
 else
  if $next_is_out ; then
   outfile="$arg"
   next_is_out=false
  else
   for ext in $EXTS ; do
    if fnmatch '*.'$ext "$arg" ; then
     infile=$arg
    fi
    test -n "$infile" && break
   done
  fi
 fi
 $minus_c_seen && test -n "$infile" && test -n "$outfile" && break
done
if ! $minus_c_seen || test -z "$infile" ; then
 $verbose && printf "%s: no -c in command line, running compiler directly\n" "$toolname"
 exec $CALL_COMPILER "$@"
fi
if test -z "$outfile" ; then
 # compiler called without -o foo.o - derive default .o filename from inputfile
 outfile="${infile%%${infile##*.}}"o
fi
cmdline=
for i ; do cmdline="$cmdline $(quote "$i")" ; done
opts_hash=$(printf "%s\n" "$cmdline" | getmd5)
if test -r "$outfile.cachedat" && test -r "$outfile" ; then
 exec 3<"$outfile.cachedat"
 read cached_opts <&3
 if test $cached_opts != $opts_hash ; then
  $verbose && printf "%s: command line for %s has changed, recompile required\n" "$toolname" "$infile"
  recompile "$@"
 fi
 while read depline <&3 ; do
  hash=$(printf "%s\n" "$depline" | cut -d ':' -f 1)
  fn=$(printf "%s\n" "$depline" | sed 's/^'$hash'://')
  if test $(getmd5f "$fn") != $hash ; then
    $verbose && printf "%s: %s has changed contents, recompile required\n" "$toolname" "$fn"
    recompile "$@"
  fi
 done
 exec 3<&-
 $verbose && printf "%s: %s and dependencies unchanged.\n" "$toolname" "$infile"
 exec touch "$outfile"
else
 $verbose && printf "%s: output file or cache missing, need compile\n" "$toolname"
 recompile "$@"
fi
```

so if i need to check out another branch just to look at git commits i dont have the recompile everything all over again because git modifies the timestamps.

**Comment by ivan-mogilko** [comment]
> Problem is it has proper things so it's nice to work with it. Removing things will make the experience less pleasant - it has proper comments I don't feel like filtering with the preprocessor - I like the comments on my IDE!

Erm, I did not suggest to remove anything from the headers, I meant simply - include the headers that we need.

@rofl0r I edited your comment and hid the script under spoiler, because it's pretty long and is not relevant to this discussion.

**Comment by ericoporto** [comment]
@ivan-mogilko I did had the impression that picking dependencies was going to be easy, but once I started to actually try to do it wasn't as simple.

This is a "Windows doesn't have a standard way of getting dependencies" problem. Because it's a header library it's pretty non issue in other OSes (it's a build but not a runtime dependency), and they also have package managers.

I scanned [MS repos to see what they do in the cpp repos](https://github.com/microsoft?language=c%2B%2B&page=1) that they do use standard VS `.sln` files, and I couldn't see a pattern to follow. The alternative I have is adding a line in the Windows instructions, adding a prop file, and preplacing the dependency somewhere in the Windows Docker image, with appropriate environment variables.

**Comment by ivan-mogilko** [comment]
> Ctrl+Alt+X doesn't abort the game.

It should be Alt + X, but I think it's fixed, please try again with latest branch.

Also just fixed: event polling was missing during video playback (were not able to skip and even close window).

**Comment by ivan-mogilko** [comment]
>  Mouse Middle Click

Fixed, there was a typo: 7293b69e3e0c75594118c8104a55d9b32e5db2d1

**Comment by ivan-mogilko** [comment]
> I don't know if others have this issue, but errors place the pop-up window behind the game window and if the game is Fullscreen I can't close it or load task manager, having to restart my computer.

This works for me now if I abort game with alt+X, but there was definitely a problem with Direct3D on Windows.
In any case, if this is still an issue, please specify on which system and with which graphic renderer do you experience this problem.

**Comment by ericoporto** [comment]
It was on Windows at the time, with Direct3D. I haven't checked recently.

**Comment by ivan-mogilko** [comment]
Marked Android tasks complete (as far as I understand that).

Pushed support for resizing windows on desktop systems (need to test more of course).

**Comment by rofl0r** [comment]
btw, SDL2 offers 2 different fullscreen modes - one that switches the actual desktop resolution and another one that scales up to desktop size. as i understand it you opted for the latter - though it might be advantageous for slow machines to offer the other method as an option. maybe a flag in acsetup.cfg that decides which fullscreen mode to use ?

**Comment by ivan-mogilko** [comment]
> btw, SDL2 offers 2 different fullscreen modes - one that switches the actual desktop resolution and another one that scales up to desktop size. as i understand it you opted for the latter - though it might be advantageous for slow machines to offer the other method as an option. maybe a flag in acsetup.cfg that decides which fullscreen mode to use ?

SDL modes are used only for the SDL-based software renderer now, but true, I think this should be added in todo.

**Comment by jnahmias** [comment]
Hi @ericoporto,
Do you need help with updating the debian packaging for ags? I started looking into SDL_sound and it seems that support for SDL2 will be in an upcoming release. That will allow pulling that into a proper Debian package so it doesn't need to be statically linked in. Are there any other blockers?
--Joe

**Comment by ya-isakov** [comment]
I'm sorry, but are there plans to support system SDL2?

**Comment by ya-isakov** [comment]
I'm sorry, but I cannot achieve that - it's fetching libsdl2 from the internet, and building it as a part of ags building https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/CMakeLists.txt#L165, and https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/CMake/FetchSDL2.cmake

**Comment by rofl0r** [comment]
```
cd Engine
make
```
you don't need CMake.

**Comment by ya-isakov** [comment]
Yes, thank you, but it fails to compile, as it cannot find sdl-sound. And from what I see, sdl2-sound is not available yet. I'll try to install it from hg.

**Comment by ya-isakov** [comment]
I've managed to build SDL2 version, even with CMake (with small changes) using system SDL2. I want to do a MR with these changes, but what is the main (and supported) build system - is it CMake or manually-written make files?

**Comment by ivan-mogilko** [comment]
The CMake, because it's meant to configure all engine ports. Makefiles were left as a backup, because they are easier for some users on Linux.

**Comment by ya-isakov** [comment]
So, are there plans to allow Cmake build with system SDL2, and static sdl2-sound? I can try to do a MR...

**Comment by rofl0r** [comment]
> are there plans to allow Cmake build with system SDL2, and static sdl2-sound?

doesn't cmake allow you configurable options, like configure-style --with-system-sdl2 ?
i think i've seen something like that when configuring cmake stuff with `ccmake`.

**Comment by ivan-mogilko** [comment]
> So, are there plans to allow Cmake build with system SDL2, and static sdl2-sound? I can try to do a MR...

I cannot tell about the plans, but if something is beneficial, then it may be added as an option.

sdl2-sound will be released eventually and then it may possibly be taken from the system too.

**Comment by ericoporto** [comment]
hey, with the Software driver, when I try to alternate between Windowed and Fullscreen (doesn't matter which one started), the `virtualScreen` from the `SDLRendererGraphicsDriver` is becoming null and crashing for me (I tested on Ubuntu 20.04). This doesn't happen with other gfx drivers.

Is this happening with any of you?

**Comment by ivan-mogilko** [comment]
@ericoporto 
> hey, with the Software driver, when I try to alternate between Windowed and Fullscreen (doesn't matter which one started), the `virtualScreen` from the `SDLRendererGraphicsDriver` is becoming null and crashing for me (I tested on Ubuntu 20.04). This doesn't happen with other gfx drivers.
> 
> Is this happening with any of you?

Yes, some logic is broken there compared to 3.5.*, it deletes virtual screen when display mode is changed but does not recreate it. I need to check this out.

**Comment by ivan-mogilko** [comment]
Pushed couple of fixes 42f616755a9ca59b68324d831ea4228a512cab77 and 8c1ed36a2a5c118c57da7889f890b874c4e90aa3

**Comment by ericoporto** [comment]
Thanks, I will test it. I wasn't sure if it was it or my machine - had some video driver problems on this weekend.

**Comment by ericoporto** [comment]
I remembered something reggarding MIDI, the most recent version of SDL Sound [here (at this time)](https://hg.icculus.org/icculus/SDL_sound/file/4b78007f035f
) has brought back actual timidity for MIDI playback, which fixes distortions.

Independently of this change, Windows users using the SDL2 port are required (in comparison to allegro4 branch) to do something like: http://dusted.dk/pages/playingMidiOnWindows/ 

I also updated the list at the top so it's a bit more readable.

**Comment by ivan-mogilko** [comment]
In regards to Linux, there's still a section in README that mentions midi patches from allegro site. I put a "fixme" comment there because I don't know how SDL midi works and whether anything similar is required.

**Comment by rofl0r** [comment]
> the most recent version of SDL Sound here (at this time) has brought back actual timidity for MIDI playback

actually they've thrown out modplug midi (after i fixed their code) and replaced it with timidity. whether that was a good move remains to be seen.

> I put a "fixme" comment there because I don't know how SDL midi works and whether anything similar is required.

a timidity.cfg is required that has a correct setup pointing to a set of GUS-style midi patterns or a more modern soundfont. i guess it can't hurt to link to the patchset you previously recommended, unless it's incompatible (but iirc it isnt).

**Comment by ivan-mogilko** [comment]
Found and fixed a major memory leak in the new audio system: f14e178d71e5759bd8109181f00ae2052801093c

Following game script helps to observe the issue:
<pre>
function room_RepExec() {
	if (IsKeyPressed(eKeySpace)) {
		atest.Play();
	}
}

function on_key_press(eKeyCode key) {
	atest.Play();
}
</pre>

Simply holding a space key would crash a game in few seconds. After the fix the memory seem to no longer grow when the audio gets restarted.

**Comment by ericoporto** [comment]
@ivan-mogilko can you revise the list above and see if there's anything that has already been fixed that I didn't pickup?

**Comment by ivan-mogilko** [comment]
There's a bug report recently that 3.6.0 always starts in a minimal-sized window on mac. But maybe at this point it's better to begin opening separate tickets for each problem.

**Comment by ivan-mogilko** [comment]
@ericoporto may we try enabling an OpenGL renderer for mac port? If it uses GLAD to load, like on Windows and Linux, then supposedly the engine will not fail completely if OpenGL is not supported on the machine and will be able to fallback to SDL software renderer.

**Comment by ivan-mogilko** [comment]
In regards to things fixed, this was fixed some time ago:
> Editor doesn't put SDL2.dll together in the directory
but this will have to be changed again if we statically link

and I dont know about this one:
> Sound subsystem and thread has to be explicitly stopped on exit before shutting down backend and deleting data, otherwise there may be errors.

Probably missed this, or dont remember. Is this still an issue?

**Comment by ericoporto** [comment]
> may we try enabling an OpenGL renderer for mac port

Sure, I will look into it, I will get a PR for this tomorrow.

> >Sound subsystem and thread has to be explicitly stopped on exit before shutting down backend and deleting data, otherwise there may be errors.

> Probably missed this, or dont remember. Is this still an issue?

I don't know about this one, you asked me at time to add this in the list, so I added. 😬

**Comment by ericoporto** [comment]
@ivan-mogilko I did a version here that has OpenGL enabled for MacOS and can safely fail and use Software renderer if needed
https://github.com/ericoporto/ags/tree/feature-macos-opengl

I moved things around to account for shader failing to compile, which should not be a problem - it should not fail on real hardware but I do have a MacOS VM that doesn't have good OpenGL support and it does.

**Comment by ivan-mogilko** [comment]
Okay, this one looks like complete now:
> Sound subsystem and thread has to be explicitly stopped on exit before shutting down backend and deleting data, otherwise there may be errors.

**Comment by ericoporto** [comment]
> Found bug in new sound backend: it does not have a proper cancellation in case it failed to decode sound data.
If the clip is told to play repeatedly it gets into infinite loop trying to fill the buffer over and over again.

@ivan-mogilko do you remember what that was? Does this bug still exists?

**Comment by ivan-mogilko** [comment]
> do you remember what that was? Does this bug still exists?

It should still be there I think, I'll try to address this in following days.

**Comment by ivan-mogilko** [comment]
> > Found bug in new sound backend: it does not have a proper cancellation in case it failed to decode sound data.
If the clip is told to play repeatedly it gets into infinite loop trying to fill the buffer over and over again.

Ok I think this one is covered now.

Also made decoder pre-init sound sample and return error on failure, this restores original AudioClip.Play behavior in script too.

**Comment by ericoporto** [comment]
I think this issue has been running for a long time, we can split things that are needed to it's own issues and look into closing this one. When I wrote it, I meant it to just get the ball running for CI, build instructions and dependencies on the different platforms, and things that could be minor regressions. I think this is done.

**Comment by ericoporto** [comment]
I pulled some remaining items on the list to their own issues.

Regarding the remaining ones:

- Android touch controls, #275, #862 and #1538 already cover a good ground.
- MacOS deserves more testing and the build instruction could use more info, but I think what we have is sufficient for now
- The Linux icon issue I can't figure out how to do it without adding a dependency on X11 or how to work it out on Wayland, it would be nicer with a pure SDL2 solution, but also not sure how it works on there, I am choosing to not open such issue right now.

I think any additional discussion could have it's own issue if needed.
