### ISSUE TITLE
AGS4: Deprecated API checklist

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1810]
A list of script APIs that were within deprecated blocks in agsdefns.sh from last time I was cleaning up the code from old unused functions. Should come handy for the next round.
Note: not all of these are necessarily to be removed, some are still used under the hood by the newer iterations.

### Global
- [x] import void SetGlobalString(int stringID, const string newValue);
- [x] import void GetGlobalString(int stringID, string buffer);
- [?] import void InputBox(const string prompt, string buffer); // USEFUL for quick debugging, no direct alternative
- [x] import int  GetTranslationName (string buffer);
- [x] import int  GetSaveSlotDescription(int slot, string buffer);
- [x] import void GetLocationName(int x, int y, string buffer);
- [x] import void GetRoomPropertyText(const string property, string buffer);
- [x] import int  GetHotspotAt(int x, int y);
- [x] import int  GetObjectAt(int x,int y);
- [x] import int  GetCharacterAt(int x,int y);
- [x] import int  GetRegionAt (int x, int y);
- [x] import int  GetInvAt(int x,int y);
- [x] import int  GetTime(int whichValue);
- [x] import int  GetRawTime();
- [x] import int  LoadSaveSlotScreenshot(int saveSlot, int width, int height);
- [x] import int  LoadImageFile(const string filename);
- [x] import void DeleteSprite(int spriteSlot);
- [x] import void SetSpeechFont(FontType);
- [x] import void SetNormalFont(FontType);
- [x] import int  GetGameParameter(int parameter, int data1=0, int data2=0, int data3=0);
- [x] import void SetDialogOption(int topic, int option, DialogOptionState);
- [x] import DialogOptionState GetDialogOption(int topic, int option);
- [x] import void RunDialog(int topic);

### String functions
- [x] import void StrCat(string main, const string newbit);
- [x] import int  StrCaseComp(const string str1, const string str2);
- [x] import int  StrComp(const string str1, const string str2);
- [x] import void StrCopy(string dest, const string source);
- [x] import void StrFormat(string dest, const string format, ...);
- [x] import int  StrLen(const string);
- [x] import int  StrGetCharAt (const string, int position);
- [x] import void StrSetCharAt (string, int position, int newChar);
- [x] import void StrToLowerCase (string);
- [x] import void StrToUpperCase (string);
- [x] import int  StrContains (const string haystack, const string needle);
- [x] import void ParseText (const string);
- [x] import int  SaidUnknownWord (string buffer);
- [x] import void GetMessageText (int messageNumber, string buffer);
- [x] import int  StringToInt(const string);

### Overlays
- [x] import int  CreateGraphicOverlay(int x, int y, int slot, bool transparent);
- [x] import int  CreateTextOverlay(int x, int y, int width, FontType, int colour, const string text, ...);
- [x] import void SetTextOverlay(int overlayID, int x, int y, int width, FontType, int colour, const string text, ...);
- [x] import void RemoveOverlay(int overlayID);
- [x] import int  MoveOverlay(int overlayID, int x, int y);
- [x] import int  IsOverlayValid(int overlayID);

### Obsolete GUI functions
- [x] import int  InventoryScreen();
- [x] import void SetInvDimensions(int width, int height);
- [x] import int  GetGUIAt (int x, int y);
- [x] import int  GetGUIObjectAt (int x, int y);
- [-] import void InterfaceOn(int gui); // NO DIRECT ALTERNATIVE 
- [-] import void InterfaceOff(int gui); // NO DIRECT ALTERNATIVE
- [x] //import void GUIOn (int gui);
- [x] //import void GUIOff (int gui);
- [x] import void SetGUIPosition(int gui, int x, int y);
- [x] import void SetGUISize(int gui, int width, int height);
- [x] import void CentreGUI(int gui);
- [x] import int  IsGUIOn (int gui);
- [x] import void SetGUIBackgroundPic (int gui, int spriteSlot);
- [x] import void SetGUITransparency(int gui, int amount);
- [x] import void SetGUIClickable(int gui, int clickable);
- [x] import void SetGUIZOrder(int gui, int z);
- [x] import void SetGUIObjectEnabled(int gui, int object, int enable);
- [x] import void SetGUIObjectPosition(int gui, int object, int x, int y);
- [x] import void SetGUIObjectSize(int gui, int object, int width, int height);
- [x] import void SetLabelColor(int gui, int object, int colour);
- [x] import void SetLabelText(int gui, int object, const string text);
- [x] import void SetLabelFont(int gui, int object, FontType);
- [x] import void SetButtonText(int gui, int object, const string text);
- [x] import void SetButtonPic(int gui, int object, int which, int spriteSlot);
- [x] import int  GetButtonPic(int gui, int object, int which);
- [x] import void AnimateButton(int gui, int object, int view, int loop, int delay, int repeat);
- [x] import void SetSliderValue(int gui, int object, int value);
- [x] import int  GetSliderValue(int gui, int object);
- [x] import void SetTextBoxFont(int gui, int object, FontType);
- [x] import void GetTextBoxText(int gui, int object, string buffer);
- [x] import void SetTextBoxText(int gui, int object, const string text);
- [x] import void ListBoxClear(int gui, int object);
- [x] import void ListBoxAdd(int gui, int object, const string text);
- [x] import int  ListBoxGetSelected(int gui, int object);
- [x] import void ListBoxGetItemText(int gui, int object, int listIndex, string buffer);
- [x] import void ListBoxSetSelected(int gui, int object, int listIndex);
- [x] import void ListBoxSetTopItem (int gui, int object, int listIndex);
- [x] import void ListBoxDirList (int gui, int object, const string fileMask);
- [x] import int  ListBoxGetNumItems (int gui, int object);
- [x] import int  ListBoxSaveGameList (int gui, int object);
- [x] import void ListBoxRemove (int gui, int object, int listIndex);

### mouse functions
- [x] import void ChangeCursorGraphic(int mode, int slot);
- [x] import void ChangeCursorHotspot(int mode, int x, int y);
- [x] import int  GetCursorMode();
- [x] import void SetCursorMode(CursorMode);
- [x] import void SetNextCursorMode();
- [x] import void SetDefaultCursor();
- [x] import void SetMouseCursor(CursorMode);
- [x] import void SetMouseBounds(int left, int top, int right, int bottom);
- [x] import void SetMousePosition(int x, int y);
- [x] import void ShowMouseCursor();
- [x] import void HideMouseCursor();
- [x] import void RefreshMouse();
- [x] import void DisableCursorMode(CursorMode);
- [x] import void EnableCursorMode(CursorMode);
- [x] import void SaveCursorForLocationChange();
- [ ] import int  IsButtonDown(MouseButton);

### Obsolete functions for objects
- [x] import void MergeObject(int object);
- [x] import void SetObjectTint(int object, int red, int green, int blue, int saturation, int luminance);
- [x] import void RemoveObjectTint(int object);
- [x] import void StopObjectMoving(int object);
- [x] import void RunObjectInteraction (int object, CursorMode);
- [x] import int  GetObjectProperty(int object, const string property);
- [x] import void GetObjectPropertyText(int object, const string property, string buffer);
- [x] import void AnimateObject(int object, int loop, int delay, int repeat);
- [x] import void AnimateObjectEx(int object, int loop, int delay, int repeat, int direction, int blocking);
- [x] import void ObjectOff(int object);
- [x] import void ObjectOn(int object);
- [x] import void SetObjectBaseline(int object, int baseline);
- [x] import int  GetObjectBaseline(int object);
- [x] import void SetObjectFrame(int object, int view, int loop, int frame);
- [x] import void SetObjectGraphic(int object, int spriteSlot);
- [x] import void SetObjectView(int object, int view);
- [x] import void SetObjectTransparency(int object, int amount);
- [x] import void MoveObject(int object, int x, int y, int speed);
- [x] import void MoveObjectDirect(int object, int x, int y, int speed);
- [x] import void SetObjectPosition(int object, int x, int y);
- [x] import int  AreObjectsColliding(int object1, int object2);
- [x] import void GetObjectName(int object, string buffer);
- [x] import int  GetObjectX(int object);
- [x] import int  GetObjectY(int object);
- [x] import int  GetObjectGraphic(int object);
- [x] import int  IsObjectAnimating(int object);
- [x] import int  IsObjectMoving(int object);
- [x] import int  IsObjectOn (int object);
- [x] import void SetObjectClickable(int object, int clickable);
- [x] import void SetObjectIgnoreWalkbehinds (int object, int ignore);

### Obsolete Character functions
- [x] import void AddInventory(int item);
- [x] import void AddInventoryToCharacter(CHARID, int item);
- [x] import void AnimateCharacter (CHARID, int loop, int delay, int repeat);
- [x] import void AnimateCharacterEx (CHARID, int loop, int delay, int repeat, int direction, int blocking);
- [x] import int AreCharactersColliding(CHARID, CHARID);
- [x] import int AreCharObjColliding(CHARID, int object);
- [x] import void ChangeCharacterView(CHARID, int view);
- [x] import void DisplaySpeech (CHARID, const string message, ...);
- [x] import void DisplaySpeechAt (int x, int y, int width, CHARID, const string message);
- [x] import int DisplaySpeechBackground(CHARID, const string message);
- [x] import void DisplayThought (CHARID, const string message, ...);
- [x] import void FaceCharacter(CHARID, CHARID toFace);
- [x] import void FaceLocation(CHARID, int x, int y);
- [x] import void FollowCharacter(CHARID sheep, CHARID shepherd);
- [x] import void FollowCharacterEx(CHARID sheep, CHARID shepherd, int dist, int eagerness);
- [x] import int GetCharacterProperty(CHARID, const string property);
- [x] import void GetCharacterPropertyText(CHARID, const string property, string buffer);
- [x] import int GetPlayerCharacter();
- [x] import void LoseInventory(int item);
- [x] import void LoseInventoryFromCharacter(CHARID, int item);
- [x] import void MoveCharacter(CHARID, int x, int y);
- [x] import void MoveCharacterBlocking(CHARID, int x, int y, int direct);
- [x] import void MoveCharacterDirect(CHARID, int x, int y);
- [x] import void MoveCharacterPath(CHARID, int x, int y);
- [x] import void MoveCharacterStraight(CHARID, int x,int y);
- [x] import void MoveCharacterToHotspot(CHARID, int hotspot);
- [x] import void MoveCharacterToObject(CHARID, int object);
- [x] import void MoveToWalkableArea(CHARID);
- [x] import void NewRoom(int roomNumber);
- [x] import void NewRoomEx(int roomNumber, int x, int y);
- [x] import void NewRoomNPC(CHARID, int roomNumber, int x, int y);
- [x] import void ReleaseCharacterView(CHARID);
- [x] import void RunCharacterInteraction (CHARID, CursorMode);
- [x] import void SetActiveInventory(int item);
- [x] import void SetCharacterBaseline(CHARID, int baseline);
- [x] import void SetCharacterBlinkView(CHARID, int view, int interval);
- [x] import void SetCharacterClickable(CHARID, int clickable);
- [x] import void SetCharacterFrame(CHARID, int view, int loop, int frame);
- [x] import void SetCharacterIdle(CHARID, int idleView, int delay);
- [x] import void SetCharacterIgnoreLight (CHARID, int ignoreLight);
- [x] import void SetCharacterIgnoreWalkbehinds (CHARID, int ignoreWBs);
- [x] import void SetCharacterProperty (CHARID, int property, int newValue);
- [x] import void SetCharacterSpeechView(CHARID, int view);
- [x] import void SetCharacterSpeed(CHARID, int speed);
- [x] import void SetCharacterSpeedEx(CHARID, int x_speed, int y_speed);
- [x] import void SetCharacterTransparency(CHARID, int transparency);
- [x] import void SetCharacterView(CHARID, int view);
- [x] import void SetCharacterViewEx(CHARID, int view, int loop, int align);
- [x] import void SetCharacterViewOffset(CHARID, int view, int x_offset, int y_offset);
- [x] import void SetPlayerCharacter(CHARID);
- [x] import void SetTalkingColor(CHARID, int colour);
- [x] import void StopMoving(CHARID);

### obsolete file I/O functions
- [x] import int  FileOpen(const string filename, const string mode);
- [x] import void FileWrite(int fileHandle, const string text);
- [x] import void FileWriteRawLine(int fileHandle, const string text);
- [x] import void FileRead(int fileHandle, string buffer);
- [x] import void FileClose(int fileHandle);
- [x] import void FileWriteInt(int fileHandle, int value);
- [x] import int  FileReadInt(int fileHandle);
- [x] import char FileReadRawChar(int fileHandle);
- [x] import void FileWriteRawChar(int fileHandle, int value);
- [x] import int  FileReadRawInt(int fileHandle);
- [x] import int  FileIsEOF(int fileHandle);
- [x] import int  FileIsError(int fileHandle);

### obsolete hotspot/region funcs
- [x] import void DisableHotspot(int hotspot);
- [x] import void EnableHotspot(int hotspot);
- [x] import void GetHotspotName(int hotspot, string buffer);
- [x] import int  GetHotspotPointX(int hotspot);
- [x] import int  GetHotspotPointY(int hotspot);
- [x] import int  GetHotspotProperty(int hotspot, const string property);
- [x] import void GetHotspotPropertyText(int hotspot, const string property, string buffer);
- [x] import void RunHotspotInteraction (int hotspot, CursorMode);
- [x] import void DisableRegion(int region);
- [x] import void EnableRegion(int region);
- [x] import void RunRegionInteraction (int region, int event);
- [x] import void SetAreaLightLevel(int area, int lightLevel);
- [x] import void SetRegionTint(int area, int red, int green, int blue, int amount);

### obsolete inv functions
- [x] import int  GetInvProperty(int invItem, const string property);
- [x] import void GetInvPropertyText(int invItem, const string property, string buffer);
- [x] import void GetInvName(int item, string buffer);
- [x] import int  GetInvGraphic(int item);
- [x] import void SetInvItemPic(int item, int spriteSlot);
- [x] import void SetInvItemName(int item, const string name);
- [x] import int  IsInventoryInteractionAvailable (int item, CursorMode);
- [x] import void RunInventoryInteraction (int item, CursorMode);

### obsolete raw draw stuff
- [x] import void RawClearScreen (int colour);
- [x] import void RawDrawCircle (int x, int y, int radius);
- [x] import void RawDrawImage (int x, int y, int spriteSlot);
- [x] import void RawDrawImageOffset(int x, int y, int spriteSlot);
- [x] import void RawDrawImageResized(int x, int y, int spriteSlot, int width, int height);
- [x] import void RawDrawImageTransparent(int x, int y, int spriteSlot, int transparency);
- [x] import void RawDrawLine (int x1, int y1, int x2, int y2);
- [x] import void RawDrawRectangle (int x1, int y1, int x2, int y2);
- [x] import void RawDrawTriangle (int x1, int y1, int x2, int y2, int x3, int y3);
- [x] import void RawPrint (int x, int y, const string message, ...);
- [x] import void RawPrintMessageWrapped (int x, int y, int width, FontType, int messageNumber);
- [x] import void RawSetColor(int colour);
- [x] import void RawSetColorRGB(int red, int green, int blue);
- [x] import void RawDrawFrameTransparent (int frame, int transparency);
- [x] import void RawSaveScreen ();
- [x] import void RawRestoreScreen ();
- [x] // obsolete RawRestoreScreenTinted(int red, int green, int blue, int opacity);

### OLD MUSIC/SOUND FUNCTIONS
- [x] import void PlayMusic(int musicNumber);
- [x] import void PlayMusicQueued(int musicNumber);
- [x] import void PlaySilentMIDI(int musicNumber);
- [x] import void PlayMP3File(const string filename);
- [x] import int  PlaySound(int soundNumber);
- [x] import void PlaySoundEx(int soundNumber, int channel);
- [x] import void PlayAmbientSound (int channel, int sound, int volume, int x, int y);
- [x] import void StopAmbientSound (int channel);
- [x] import int  GetCurrentMusic();
- [x] import void SetMusicRepeat(int repeat);
- [x] import void SetMusicVolume(int volume);
- [x] import void SetSoundVolume(int volume);
- [x] import void SetMusicMasterVolume(int volume);
- [x] import void SetDigitalMasterVolume(int volume);
- [x] import void SeekMODPattern(int pattern);
- [x] import void SeekMIDIPosition(int position);
- [x] import void SeekMP3PosMillis(int offset);
- [x] import int  IsChannelPlaying(int channel);
- [x] import int  IsSoundPlaying();
- [!] import int  IsMusicPlaying();
- [x] import int  GetMIDIPosition();
- [x] import int  GetMP3PosMillis();
- [x] import void SetChannelVolume(int channel, int volume);
- [ ] import void StopChannel(int channel);
- [x] import void StopMusic();
- [ ] import void SetFrameSound (int view, int loop, int frame, int sound);

### audio
- [x] LegacyMusicVolumeAdjustment
- [x] LegacyMusicMasterVolumeAdjustment
- [x] AUDIOTYPE_LEGACY_AMBIENT_SOUND
- [x] AUDIOTYPE_LEGACY_SOUND
- [x] MusicVolumeAdjustment  (an [Obsolete] property remains in Room.cs)
- [x] ST_TUNE
- [x] update_ambient_sound_vol
- [x] ????ambient_sounds_persist?????
- [x] resetLegacyMusicSettings
- [x] ViewFrame_GetSound
- [x] ViewFrame_SetSound
- [x] GetAudioClipForOldStyleNumber

### Messages

- [x] DrawingSurface.DrawMessageWrapped
- [x] Room.Messages[]
- [x] DisplayMessage
- [x] DisplayMessageAtY
- [x] DisplayMessageBar
- [x] Game.GlobalMessages[]
- [x] Game.GlobalStrings[]

**Comment by ericoporto** [comment]
Hey, there are two specific functions in this list that have no modern equivalent afaik and I find particularly useful. Should I state it here or open a new issue to request a modern redo of them? (don't want to be specific here to not change the subject)

**Comment by ivan-mogilko** [comment]
> Hey, there are two specific functions in this list that have no modern equivalent afaik and I find particularly useful. Should I state it here or open a new issue to request a modern redo of them? (don't want to be specific here to not change the subject)

Yes of course, if there are no equiv at all, then we should keep them until we have a "remake".

**Comment by ericoporto** [comment]
AreCharObjColliding, AreCharactersColliding, and AreObjectsColliding, they even were mentioned today in the forums. I use these quite frequently when doing arcade like stuff. They are ancient, and perhaps proper substitute would be a basic collision system, but they are fast and useful.

**Comment by ivan-mogilko** [comment]
> AreCharObjColliding, AreCharactersColliding, and AreObjectsColliding,

There are Character.IsCollidingWithChar, Character.IsCollidingWithObject and Object.IsCollidingWithObject, I think these are direct equivalents?

**Comment by ericoporto** [comment]
Oh, I missed those... And I think I wrote that table. So it's all good.

**Comment by ivan-mogilko** [comment]
I removed a bunch of stuff recently, see commit: 5b81b4f23b81fd296df51455f24efb14f1a1859b

I think what remains is functions in "global_" cpps which are in use because they are called from the OOP-style functions.
So they have to be merged for a complete clean up.

**Comment by ivan-mogilko** [comment]
Removed Global Messages and Room Messages (#2184), updated list.

**Comment by ivan-mogilko** [comment]
I should note that besides cleaning the api header these should also be removed from the exports table in the engine.
Recently, I found that there's a number of deprecated functions that are still being registered by the engine. Might have to scan the exports table in "global_api.cpp" for those.

**Comment by ivan-mogilko** [comment]
I think I finished this.

There is still a number of very old script functions in global namespace, but these either
- have no direct equivalent
- deprecated only relatively recently in ags 4 (walkable area and walk-behind api)
