### ISSUE TITLE
3.5.0: CI checklist

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#800]
**Windows:**

Tasks:

- [x] Build Editor
- [x] Build Engine
- [x] Package zip archive
- [x] Build installer
- [x] Package zip archive with PDB files (for debugging crash dumps)

**Linux**

- (?) Package sources tar.xz from release tag
- [x] Build engine + libraries
- [x] Package tar.xz for linux users
~- [ ] Package zip for adding to the Editor (for building linux versions of games)~

**Android**

- [x] Build native engine libraries
- [x] Package engine libraries (for use in creating signed game APKs)
- [x] Build and package universal Launcher APK (for running random games)

**Final artifacts:**

- [x] (Windows) AGS Editor installer (+ Linux build pack)
- [x] (Windows) AGS Editor in zip (+ Linux build pack)
- [x] (Windows) PDBs in zip
~- [] (Windows) Linux pack in zip (merged with Editor zip)~
- (?) (Linux) Sources in tar.xz
- [x] (Linux) Prebuilt binaries in tar.xz
- [x] (Android) Launcher APK in zip
- [x] (Android) native Engine libraries in zip

Anything else?

**Comment by ericoporto** [comment]
Decide which CI (or CIs) to use.

**Comment by ivan-mogilko** [comment]
Does anyone know, what is required to set up automatic building for Windows? Which service do we use for that (I lost track of them tbh)?

**Comment by morganwillcock** [comment]
There isn't a Windows build setup at the moment, but at the moment other builds are split between Travis CI (for Linux and macOS) and AppVeyor (for Windows). The direct requirement to set everything up is to workout where dependencies are coming from, and which of these are built and hosted as releases in this organisation vs just downloaded from some external source). i.e. main requirement at the moment is making CI builds for Allegro where they are needed. Secondary requirement is safely storing any passwords and keys for these CI services ,or any other external services we are using.

I'll look at these CI items now (the game build process changes I wanted to make for the Editor are probably too large/different for the 3.5 release).

**Comment by morganwillcock** [comment]
A few items that I think are not covered in this list:

- The game templates that ship with the Editor. These will not compile from source since there is only a switch to compile source as a game, not to compile source as a template. Also, there is no guarantee that the Editor will open in a CI environment - in a Windows container I imagine it wouldn't work. The easiest way around this for the time being is probably just to manually make a release on Github and then download it from there as part of the build.

- This doesn't say where the included manual is coming from. I presume everyone agrees to use the new one from this point onwards?

- Since this will be automated, we should probably add an extra step to publish checksums for the files which are presented for distribution, so people can verify what they are getting if the files get uploaded somewhere else.

**Comment by morganwillcock** [comment]
Other than Android, I have a working build process on Cirrus CI which covers everything here. In order to submit a PR which build successfully I think I need to:

- configure the Cirrus CI 'GitHub App' within the ags and lib-allegro repositories (possibly I would change the default repository for lib-allegro at this point too, since by default it currently looks at an old branch)
- configure the CI user for permission to upload releases (generate a new token)
- generate a new lib-allegro release (it is referenced and cached in the build process)

I thought I should check before I start, that no-one has any objections?

**Comment by ericoporto** [comment]
Update badges linking to CI services

**Comment by ivan-mogilko** [comment]
There are two minor things I noticed in recent build:

* Changes.txt becomes lowercase when added to distributed files (idk if important).
* There are *.xml files accompanying couple of dlls, such as AGS.Types.xml, and I am not sure if these are necessary; editor runs well without one.

**Comment by morganwillcock** [comment]
These things are not specific to CI builds, but I'll change them.

https://github.com/adventuregamestudio/ags/blob/373b9867ec37710f033dee1842bd98fbf416f6a1/Windows/Installer/build.ps1#L25

https://github.com/adventuregamestudio/ags/blob/373b9867ec37710f033dee1842bd98fbf416f6a1/Windows/Installer/ags.iss#L83-L99

**Comment by ivan-mogilko** [comment]
I may be unexperienced with Cirrus CI, but I found it a little difficult to track all the available final artifacts.

Is it possible to create an extra task which only purpose is to gather a list of final artifacts from all the previous jobs (similar to the "Final artifacts" list in the first post above)?

**Comment by morganwillcock** [comment]
I think this is possible, I'll give it a try.

**Comment by morganwillcock** [comment]
I've tested querying, listing, and optionally downloading the build artifacts as an independent script. I'll add this separately and modify the build tasks to use it, and at that point it should be pretty easy to just list all artifacts as a separate task or task item.

I'll also add source archives for use with external packaging systems, although I'm not entirely sure whether this should include all git submodules or not. Possibly it depends on the state of the Lua plug-in?

**Comment by ericoporto** [comment]
Googletests is also a submodule.

**Comment by morganwillcock** [comment]
I've added the Android library zip file in https://github.com/adventuregamestudio/ags/commit/953ac85f6bfbc05b9367da28805690d94fdbbb33 so the release list is now:
<pre>AGS-3.5.0.18-RC2.exe
AGS-3.5.0.18-RC2.zip
AGS-3.5.0.18-android-libs.zip
AGS-3.5.0.18-debug.apk
AGS-3.5.0.18-pdb.zip
ags_3.5.0.18_amd64.deb
ags_3.5.0.18_i386.deb
ags_3.5.0.18_linux.tar.gz
ags_3.5.0.18_source.tar.bz2
ags_3.5.0.18_source.tar.gz
ags_3.5.0.18_source.tar.xz
ags_3.5.0.18_source.zip</pre>

So if we say that source distribution is covered for all platforms by at least one of these source archives (e.g. someone might want to create a binary package for macOS in a similar way that one might be created for a Linux distribution), then I think the list is now complete.

**Comment by ivan-mogilko** [comment]
Great, the main bulk is done then.
